<?php

namespace MDB\AssetBundle\Repository;

use Gedmo\Tree\Document\MongoDB\Repository\MaterializedPathRepository;


/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends MaterializedPathRepository
{
}