<?php

namespace MDB\AssetBundle\Repository;

use Gedmo\Tree\Document\MongoDB\Repository\MaterializedPathRepository;


/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends MaterializedPathRepository
{
    public function findByIds($array)
    {
        return $this->createQueryBuilder('MDB\AssetBundle\Document\Asset')
            ->field('id')->in($array)
            ->getQuery()
            ->execute();
    }

    public function countAssetsByOrganization($organizationCode)
    {
        $results = $this->createQueryBuilder()
            ->group(array(), array('count' => 0))
            ->reduce('function (obj, prev) { prev.count++; }')
            ->field('organizationCode')->equals($organizationCode)
            ->getQuery()
            ->execute();

        return (int) $results['count'];
    }

}